operator:
  scyllaDBVersion: "6.2.0"
  # scyllaDBEnterpriseVersionNeedingConsistentClusterManagementOverride sets enterprise version
  # that requires consistent_cluster_management workaround for restore.
  # In the future, enterprise versions should be run as a different config instance in its own run.
  scyllaDBEnterpriseVersionNeedingConsistentClusterManagementOverride: "2024.1.11"
  scyllaDBUtilsImage: "docker.io/scylladb/scylla:6.2.0@sha256:5b53a7c60d9f9555bb87791ff29b2e633c6f472aec00de7afaf4db1addc6d594"
  scyllaDBManagerVersion: "3.5.0-dev-0.20241105.c9a79e43c"
  scyllaDBManagerAgentVersion: "3.5.0-dev-0.20241105.c9a79e43c"
  bashToolsImage: "registry.access.redhat.com/ubi9/ubi:9.4-1214.1726694543@sha256:b00d5990a00937bd1ef7f44547af6c7fd36e3fd410e2c89b5d2dfc1aff69fe99"
  grafanaImage: "docker.io/grafana/grafana:11.1.7@sha256:47d094fd9913f04cef23db752b2255db1cc40fc81acbeb9700501fb87d4e7ed1"
  grafanaDefaultPlatformDashboard: "scylladb-6.1/scylla-overview.6.1.json"
  prometheusVersion: "v2.53.2"
operatorTests:
  scyllaDBVersions:
    updateFrom: "6.2.0-rc2"
    upgradeFrom: "6.1.2"
  nodeSetupImage: "quay.io/scylladb/scylla-operator-images:node-setup-v0.0.3@sha256:c6b3de240cc5c884d5c617485bae35c51572cdfd39b6431d2e1f759c7d7feea1"
