apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla-manager-cluster
  namespace: scylla-manager
spec:
  version: 6.2.0
  agentVersion: 3.4.0-0.20241218.faf39b6f2
  repository: docker.io/scylladb/scylla
  agentRepository: docker.io/scylladb/scylla-manager-agent
  developerMode: true
  cpuset: true
  datacenter:
    name: manager-dc
    racks:
    - name: manager-rack
      members: 1
      storage:
        capacity: 5Gi
        storageClassName: scylladb-local-xfs
      resources:
        limits:
          cpu: 1
          memory: 200Mi
        requests:
          cpu: 1
          memory: 200Mi
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: scylla.scylladb.com/node-type
                operator: In
                values:
                - scylla
        tolerations:
          - effect: NoSchedule
            key: scylla-operator.scylladb.com/dedicated
            operator: Equal
            value: scyllaclusters
