# Scylla Manager image
image:
  tag: 3.5.0-dev-0.20241105.c9a79e43c
# Resources allocated to Scylla Manager pods
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 32Mi
# Resources allocated to Scylla Manager Controller pods
controllerResources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 32Mi
# Scylla instance for Manager
scylla:
  developerMode: true
  scyllaImage:
    tag: 6.2.0
  agentImage:
    tag: 3.5.0-dev-0.20241105.c9a79e43c
  datacenter: manager-dc
  racks:
    - name: manager-rack
      members: 1
      storage:
        capacity: 5Gi
        storageClassName: scylladb-local-xfs
      resources:
        limits:
          cpu: 1
          memory: 200Mi
        requests:
          cpu: 1
          memory: 200Mi
