# Version information
scyllaImage:
  tag: 6.2.0
agentImage:
  tag: 3.5.0-dev-0.20241105.c9a79e43c
# Cluster information
developerMode: true
datacenter: us-east-1
racks:
  - name: us-east-1b
    members: 2
    storage:
      capacity: 5Gi
      storageClassName: scylladb-local-xfs
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 1
        memory: 1Gi
